# Część odpowiedzialna za oprawę graficzną
# from Plot import *
# from Connection import *
# import threading


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Polacz = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Polacz.setGeometry(QtCore.QRect(40, 40, 80, 25))
        self.pushButton_Polacz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Polacz.setAccessibleDescription("")
        self.pushButton_Polacz.setObjectName("pushButton_Polacz")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Status.setGeometry(QtCore.QRect(150, 40, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Status.setFont(font)
        self.label_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Status.setObjectName("label_Status")
        self.pushButton_Rozpocznij = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Rozpocznij.setGeometry(QtCore.QRect(40, 80, 80, 25))
        self.pushButton_Rozpocznij.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Rozpocznij.setObjectName("pushButton_Rozpocznij")
        self.pushButton_temp_set = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_temp_set.setGeometry(QtCore.QRect(40, 120, 81, 51))
        self.pushButton_temp_set.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_temp_set.setObjectName("pushButton_temp_set")
        self.comboBox_temperatura = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_temperatura.setGeometry(QtCore.QRect(170, 130, 111, 25))
        self.comboBox_temperatura.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_temperatura.setEditable(False)
        self.comboBox_temperatura.setObjectName("comboBox_temperatura")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.comboBox_temperatura.addItem("")
        self.label_Regulator = QtWidgets.QLabel(self.centralwidget)
        self.label_Regulator.setGeometry(QtCore.QRect(10, 180, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Regulator.setFont(font)
        self.label_Regulator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Regulator.setObjectName("label_Regulator")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_kp = QtWidgets.QLabel(self.centralwidget)
        self.label_kp.setGeometry(QtCore.QRect(70, 210, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_kp.setFont(font)
        self.label_kp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kp.setObjectName("label_kp")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 180, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_kd = QtWidgets.QLabel(self.centralwidget)
        self.label_kd.setGeometry(QtCore.QRect(70, 240, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_kd.setFont(font)
        self.label_kd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kd.setObjectName("label_kd")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_ki = QtWidgets.QLabel(self.centralwidget)
        self.label_ki.setGeometry(QtCore.QRect(70, 270, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_ki.setFont(font)
        self.label_ki.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ki.setObjectName("label_ki")
        self.label_temp_aktualna = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_aktualna.setGeometry(QtCore.QRect(240, 250, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_aktualna.setFont(font)
        self.label_temp_aktualna.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_aktualna.setObjectName("label_temp_aktualna")
        self.pushButton_zapisz = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zapisz.setGeometry(QtCore.QRect(230, 280, 80, 25))
        self.pushButton_zapisz.setObjectName("pushButton_zapisz")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Polacz.setText(_translate("MainWindow", "Połącz"))
        self.label.setText(_translate("MainWindow", "URA - SM"))
        self.label_Status.setText(_translate("MainWindow", "Status: Rozłączono"))
        self.pushButton_Rozpocznij.setText(_translate("MainWindow", "Rozpocznij"))
        self.pushButton_temp_set.setText(_translate("MainWindow", "Temperatura \n"
"zadana"))
        self.comboBox_temperatura.setItemText(0, _translate("MainWindow", "24°C"))
        self.comboBox_temperatura.setItemText(1, _translate("MainWindow", "25°C"))
        self.comboBox_temperatura.setItemText(2, _translate("MainWindow", "26°C"))
        self.comboBox_temperatura.setItemText(3, _translate("MainWindow", "27°C"))
        self.comboBox_temperatura.setItemText(4, _translate("MainWindow", "28°C"))
        self.comboBox_temperatura.setItemText(5, _translate("MainWindow", "29°C"))
        self.comboBox_temperatura.setItemText(6, _translate("MainWindow", "30°C"))
        self.comboBox_temperatura.setItemText(7, _translate("MainWindow", "31°C"))
        self.comboBox_temperatura.setItemText(8, _translate("MainWindow", "32°C"))
        self.comboBox_temperatura.setItemText(9, _translate("MainWindow", "33°C"))
        self.comboBox_temperatura.setItemText(10, _translate("MainWindow", "34°C"))
        self.comboBox_temperatura.setItemText(11, _translate("MainWindow", "35°C"))
        self.comboBox_temperatura.setItemText(12, _translate("MainWindow", "37°C"))
        self.comboBox_temperatura.setItemText(13, _translate("MainWindow", "38°C"))
        self.comboBox_temperatura.setItemText(14, _translate("MainWindow", "39°C"))
        self.label_Regulator.setText(_translate("MainWindow", "Regulator"))
        self.label_2.setText(_translate("MainWindow", "Kp :"))
        self.label_kp.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Temperatura</p><p>aktualna:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Kd :"))
        self.label_kd.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Ki :"))
        self.label_ki.setText(_translate("MainWindow", "0"))
        self.label_temp_aktualna.setText(_translate("MainWindow", "0"))
        self.pushButton_zapisz.setText(_translate("MainWindow", "Zapisz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
